name: New Release
on:
  push:
    # Only trigger on tag pushes
    tags:
      - 'data-*' # Push events to matching data-*, i.e. data-v1.0, data-v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Extract tag name from the ref
        TAG_NAME=${GITHUB_REF#refs/tags/}

        # Get current date
        CURRENT_DATE=$(date +'%Y-%m-%d')

        # Create the release
        gh release create "$TAG_NAME" \
          --title "Release $TAG_NAME" \
          --notes "New UN data release, date data was fetched: $CURRENT_DATE" \
          --latest