name: Update UN population data
on:
  schedule:
    - cron: "7 1 1,15 1,5,8,10,11 ?"
  push:
    branches:
      - main

jobs:
  build_catalog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: undata-env
          environment-file: environment.yml
          python-version: 3.11
          auto-activate-base: false

      - name: Run python script
        working-directory: ./src
        shell: bash -l {0}
        run: |
          python fetch_un_data.py ${{ secrets.UN_API_TOKEN }}

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Update UN data on $(date +'%Y-%m-%d')"
          git push

          # Create and push tag
          TAG_NAME="data-update-$(date +'%Y-%m-%d-%H%M%S')"
          git tag -a "$TAG_NAME" -m "Update UN data on $(date +'%Y-%m-%d')"
          git push origin "$TAG_NAME"